sources:
  - name: internal
    handler:
      graphql:
        endpoint: "http://localhost:3500/graphql"
        source: "./schema.graphql"
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
          Tenant: "{context.headers['tenant']}"
        connectionParams:
          Authorization: "{context.connectionParams['authorization']}"
          Tenant: "{context.connectionParams['tenant']}"
          
serve:
  fork: 1
          